# Generated by Django 3.1.1 on 2020-10-23 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.IntegerField(default=18, verbose_name='年龄'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='grade',
            field=models.IntegerField(default=5, verbose_name='年级'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(default='迷', max_length=20, verbose_name='姓名'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='score',
            field=models.FloatField(default=100, verbose_name='成绩'),
            preserve_default=False,
        ),
    ]
