# Generated by Django 3.1.1 on 2020-10-23 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201024_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='person',
            name='grade',
            field=models.IntegerField(blank=True, null=True, verbose_name='年级'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='person',
            name='score',
            field=models.FloatField(blank=True, null=True, verbose_name='成绩'),
        ),
    ]
